    lines.append('        .:=%@@@@%=-.        ' + ' ' + '      .g8"""bgd     db      `7MN.   `7MF\'MMP""MM""YMM `7MMF\'   `7MF\'.M"""bgd       ' + ' ' + '        .:=%@@@@%=-.        ')
    lines.append('      .#@@@@@@@@@@@@%.      ' + ' ' + '    .dP\'     `M    ;MM:       MMN.    M  P\'   MM   `7   MM       M ,MI    "Y       '  + ' ' + '      .#@@@@@@@@@@@@%.      ')
    lines.append('     #@@@@@@@@@@@@@@@@#.    ' + ' ' + '    dM\'       `   ,V^MM.      M YMb   M       MM        MM       M `MMb.           '   + ' ' + '     #@@@@@@@@@@@@@@@@#.    ')
    lines.append('    %@@@@@@@@@@@@@@@@@@@    ' + ' ' + '    MM           ,M  `MM      M  `MN. M       MM        MM       M   `YMMNq.       '    + ' ' + '    %@@@@@@@@@@@@@@@@@@@    ')
    lines.append('    %@*@@@@@@@@@@@@@@*@@    ' + ' ' + '    MM.          AbmmmqMA     M   `MM.M       MM        MM       M .     `MM       '    + ' ' + '    %@*@@@@@@@@@@@@@@*@@    ')
    lines.append('    %@%-%@%##%**#%@@=%@@    ' + ' ' + '    `Mb.     ,\' A\'     VML    M     YMM       MM        YM.     ,M Mb     dM       '  + ' ' + '    %@%-%@%##%**#%@@=%@@    ')
    lines.append('    .%%-+::-****:::+-%%:    ' + ' ' + '      `"bmmmd\'.AMA.   .AMMA..JML.    YM     .JMML.       `bmmmmd"\' P"Ybmmd"        '  + ' ' + '    .%%-+::-****:::+-%%:    ')
    lines.append('     .*     :%@+     #.     ' + ' ' + '                                                                                   '    + ' ' + '     .*     :%@+     #.     ')
    lines.append('     #@+-:=*%:.**+::+@#     ' + ' ' + '      db      `7MM"""YMM MMP""MM""YMM `7MM"""YMM  `7MM"""Mq.  `7MN.   `7MF\'`7MMF\'  '  + ' ' + '     #@+-:=*%:.**+::+@#     ')
    lines.append('     =#@+-+@%=:*@#:+%%=     ' + ' ' + '     ;MM:       MM    `7 P\'   MM   `7   MM    `7    MM   `MM.   MMN.    M    MM    '   + ' ' + '     =#@+-+@%=:*@#:+%%=     ')
    lines.append('       ++:#%@%@@%%-++       ' + ' ' + '    ,V^MM.      MM   d        MM        MM   d      MM   ,M9    M YMb   M    MM    '    + ' ' + '       ++:#%@%@@%%-++       ')
    lines.append('        + -:*-++-+ *:       ' + ' ' + '   ,M  `MM      MMmmMM        MM        MMmmMM      MMmmdM9     M  `MN. M    MM    '    + ' ' + '        + -:*-++-+ *:       ')
    lines.append('        =:*=@*#%+#:=.       ' + ' ' + '   AbmmmqMA     MM   Y  ,     MM        MM   Y  ,   MM  YM.     M   `MM.M    MM    '    + ' ' + '        =:*=@*#%+#:=.       ')
    lines.append('         -#@@@@@@#=         ' + ' ' + '  A\'     VML    MM     ,M     MM        MM     ,M   MM   `Mb.   M     YMM    MM    '   + ' ' + '         -#@@@@@@#=         ')
    lines.append('           """"""           ' + ' ' + '.AMA.   .AMMA..JMMmmmmMMM   .JMML.    .JMMmmmmMMM .JMML. .JMM..JML.    YM  .JMML.  '    + ' ' + '           """"""           ')